jobs:
- template: 'azure-template-unix.yml'
  parameters:
    name: 'macOS_nightly'
    vmImage: 'macOS-latest'
    toolchain: 'nightly'

- template: 'azure-template-unix.yml'
  parameters:
    name: 'Linux_nightly'
    vmImage: 'ubuntu-latest'
    toolchain: 'nightly'

- template: 'azure-template-win.yml'
  parameters:
    name: 'Windows_nightly'
    vmImage: 'windows-latest'
    toolchain: 'nightly'
