[package]
name = "pkhexcore"
version = "0.1.0"
authors = ["Devin <devdevin541@gmail.com>", "Hector Mejia <caquillo722@gmail.com>"]
edition = "2018"

[dependencies]

log = { version = "0.4.11", features = ["release_max_level_off"] }
log-derive = "0.4.1"
num_enum = "0.5.0"
time = { version = "0.2.16", default-features = false }
deku = "0.7.2"
