[package]
name = "pkhexcore"
version = "0.1.0"
authors = ["Devin <devdevin541@gmail.com>", "Hector Mejia <caquillo722@gmail.com>"]
edition = "2018"

[dependencies]
log = "0.4"
log-derive = "0.4.1"
num_enum = "0.5.0"
async-std = "1.6.2"
time = { version = "0.2.16", default-features = false }
